# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_thongbaodangxuat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    Login = True
    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)
        self.MainWindow.show()
        sys.exit(self.app.exec_())
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 105)
        MainWindow.setMaximumSize(QtCore.QSize(270, 105))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 241, 21))
        self.label.setObjectName("label")
        self.btn_yes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yes.setGeometry(QtCore.QRect(20, 50, 100, 30))
        self.btn_yes.setObjectName("btn_yes")
        self.btn_no = QtWidgets.QPushButton(self.centralwidget)
        self.btn_no.setGeometry(QtCore.QRect(150, 50, 100, 30))
        self.btn_no.setObjectName("btn_no")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 270, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)\

        self.btn_yes.clicked.connect(self.ClickYes)
        self.btn_no.clicked.connect(self.ClickNo)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def ClickYes(self):
        self.app.quit()
        self.Login = False
    def ClickNo(self):
        self.app.quit()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thông báo"))
        self.label.setText(_translate("MainWindow", "Bạn có muốn đăng xuất không ?"))
        self.btn_yes.setText(_translate("MainWindow", "Có"))
        self.btn_no.setText(_translate("MainWindow", "Không"))


if __name__ == "__main__":
    ui = Ui_MainWindow()
